--MEMBER DUMMY 
--(because of PwdEncoder, You can not login with these accounts.)

--INSERT INTO MEMBER 
--(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, JOIN_DATE, EMAIL) 
--VALUES 
--(SEQ_MEMBER_NO.NEXTVAL, 'USER01', '1234', 'USER01', SYSDATE, 'USER01@MAIL.COM');

--INSERT INTO MEMBER 
--(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, JOIN_DATE, EMAIL) 
--VALUES 
--(SEQ_MEMBER_NO.NEXTVAL, 'USER02', '1234', 'USER02', SYSDATE, 'USER02@MAIL.COM');

--INSERT INTO MEMBER 
--(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, JOIN_DATE, EMAIL) 
--VALUES 
--(SEQ_MEMBER_NO.NEXTVAL, 'USER03', '1234', 'USER03', SYSDATE, 'USER03@MAIL.COM');

--BOARD DUMMY
INSERT INTO BOARD 
(BOARD_NO, MEMBER_NO, BOARD_CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE) 
VALUES 
(SEQ_BOARD_NO.NEXTVAL, 1, 1, 'TITLE01', 'CONTENT01', SYSDATE);

INSERT INTO BOARD 
(BOARD_NO, MEMBER_NO, BOARD_CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE) 
VALUES 
(SEQ_BOARD_NO.NEXTVAL, 1, 1, 'TITLE02', 'CONTENT02', SYSDATE);

INSERT INTO BOARD 
(BOARD_NO, MEMBER_NO, BOARD_CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE) 
VALUES 
(SEQ_BOARD_NO.NEXTVAL, 1, 1, 'TITLE03', 'CONTENT03', SYSDATE);

INSERT INTO BOARD 
(BOARD_NO, MEMBER_NO, BOARD_CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE) 
VALUES 
(SEQ_BOARD_NO.NEXTVAL, 1, 1, 'TITLE03', 'CONTENT03', SYSDATE);

INSERT INTO BOARD 
(BOARD_NO, MEMBER_NO, BOARD_CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE) 
VALUES 
(SEQ_BOARD_NO.NEXTVAL, 1, 1, 'TITLE03', 'CONTENT03', SYSDATE);

INSERT INTO BOARD 
(BOARD_NO, MEMBER_NO, BOARD_CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE) 
VALUES 
(SEQ_BOARD_NO.NEXTVAL, 1, 1, 'TITLE03', 'CONTENT03', SYSDATE);

--CATEGORY DUMMY
INSERT INTO BOARD_CATEGORY (BOARD_CATEGORY_NO, BOARD_CATEGORY_NAME)
VALUES (SEQ_BOARD_CATEGORY_NO.NEXTVAL, '자유게시판');

INSERT INTO PET_INFO 
(PET_INFO_NO, PET_INFO_TITLE, PET_INFO_CONTENT, PET_INFO_SUBCONTENT, PET_INFO_URL)
VALUES
(SEQ_PET_INFO_NO.NEXTVAL, 'DUMMY', 'DUMMMMMY', 'DUMMMDUMMMY', 'https://dummy.com');

COMMIT;

SELECT * FROM MEMBER;
SELECT * FROM BOARD;
SELECT * FROM BOARD_CATEGORY;
SELECT * FROM PET_INFO;