--MEMBER DUMMY
INSERT INTO MEMBER 
(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, JOIN_DATE, EMAIL) 
VALUES 
(SEQ_MEMBER_NO.NEXTVAL, 'USER01', '1234', 'USER01', SYSDATE, 'USER01@MAIL.COM');

INSERT INTO MEMBER 
(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, JOIN_DATE, EMAIL) 
VALUES 
(SEQ_MEMBER_NO.NEXTVAL, 'USER02', '1234', 'USER02', SYSDATE, 'USER02@MAIL.COM');

INSERT INTO MEMBER 
(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_NICK, JOIN_DATE, EMAIL) 
VALUES 
(SEQ_MEMBER_NO.NEXTVAL, 'USER03', '1234', 'USER03', SYSDATE, 'USER03@MAIL.COM');

--BOARD DUMMY
INSERT INTO BOARD 
(BOARD_NO, MEMBER_NO, BOARD_CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE) 
VALUES 
(SEQ_BOARD_NO.NEXTVAL, 1, 1, 'TITLE01', 'CONTENT01', SYSDATE);

INSERT INTO BOARD 
(BOARD_NO, MEMBER_NO, BOARD_CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE) 
VALUES 
(SEQ_BOARD_NO.NEXTVAL, 2, 2, 'TITLE02', 'CONTENT02', SYSDATE);

INSERT INTO BOARD 
(BOARD_NO, MEMBER_NO, BOARD_CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, ENROLL_DATE) 
VALUES 
(SEQ_BOARD_NO.NEXTVAL, 3, 3, 'TITLE03', 'CONTENT03', SYSDATE);

SELECT * FROM MEMBER;
SELECT * FROM BOARD;